### ISSUE TITLE
Hi facing an issue 

### ISSUE THREAD

**Issue by mrtonymu** [saifalisew1508/Telegram-Members-Adder#11]
i'm trying to scrape member on telegram but while i scrape around 5-10 user it appear this 

[!] A wait of 3571 seconds is required (caused by InviteToChannelRequest)

**Comment by saifalisew1508** [comment]
Often people facing problems like flood at the time of members adding, this happens because they do not use fresh accounts they using flooded accounts.If you want to check whether your account is flooded or not, try sending 10 messages in a public group at an interval of 1-2 second.If 10 messages go at the same time without taking time, then congratulations, your account is not flooded, then it can be said that there is a problem in the script.
